## Discussion
The best versions of the new algorithm showed good reliability and higher validity than previous approaches. However, the reliability and validity varied greatly depending on the weighting function. Only the normalized weighting function leads to improved validity over previous algorithms. Other weighting functions show slightly higher reliability, but this only underscores the improvements made by using a normalized weighting function. Even with slightly lower reliability, latencies extracted by algorithms incorporating the normalized weighting function correlated the highest with an expert ERP researcher. Using a normalized weighting window also reduces the amount of missing values, especially in combination with the penalty function. 

These results suggest that either the MINSQ or MAXCOR approach in combination with a normalized weighting function and a penalty provide the best measure of P3 latency. Even though expert researchers have been shown to provide the best measures of P3 latency before [@explorative], they do not measure the true latency without measurement error. We therefore chose to expand our validation through empirical results by a simulation study that will allow us to investigate which latency extraction measure can recover true latencies the best.